import './globals.css'

import Navbar from '@/components/common/navbar'
import AppProvider from '@/components/common/providers/app-provider'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body suppressHydrationWarning className={`${raleway.className}`}>
				<AppProvider>
					<Navbar />
					{children}
				</AppProvider>
			</body>
		</html>
	)
}
